# worker/motionanchor_worker/segmentation/sam2_bootstrap.py
"""Build a deterministic, user-controlled SAM 2 runtime bootstrap script."""

from __future__ import annotations

import json
import shutil
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

SAM2_PYTHON_VERSION = "3.12"
SAM2_CHECKPOINT_FILENAME = "sam2.1_hiera_small.pt"
SAM2_CHECKPOINT_URL = (
    "https://dl.fbaipublicfiles.com/segment_anything_2/092824/"
    "sam2.1_hiera_small.pt"
)
SAM2_CHECKPOINT_SHA256 = (
    "6d1aa6f30de5c92224f8172114de081d104bbd23dd9dc5c58996f0cad5dc4d38"
)


@dataclass(frozen=True)
class Sam2BootstrapStep:
    """One explicit installation action in execution order."""

    step_id: str
    title: str
    command: str
    already_satisfied: bool


@dataclass(frozen=True)
class Sam2BootstrapPlan:
    """Typed bootstrap contract surfaced through worker and Tauri layers."""

    schema_version: int
    ready_to_generate: bool
    target_python: str
    requirements_path: str
    checkpoint_path: str
    checkpoint_url: str
    checkpoint_sha256: str
    script_path: str
    blockers: tuple[str, ...]
    steps: tuple[Sam2BootstrapStep, ...]


def _worker_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _powershell_quote(value: Path | str) -> str:
    return "'" + str(value).replace("'", "''") + "'"


def _target_paths() -> tuple[Path, Path, Path, Path]:
    worker = _worker_root()
    environment = worker / ".venv-sam2"
    python = environment / "Scripts" / "python.exe"
    requirements = worker / "requirements-sam2-bootstrap.txt"
    checkpoint = worker / "models" / "sam2" / SAM2_CHECKPOINT_FILENAME
    return environment, python, requirements, checkpoint


def build_sam2_bootstrap_plan(script_path: str | None = None) -> Sam2BootstrapPlan:
    """Return an idempotent bootstrap plan without changing the machine."""

    environment, python, requirements, checkpoint = _target_paths()
    output = Path(script_path).expanduser() if script_path else (
        _worker_root() / "sam2-bootstrap.ps1"
    )
    blockers: list[str] = []
    launcher = shutil.which("py")
    if launcher is None and not python.is_file():
        blockers.append("Windows Python launcher 'py' is unavailable")
    if not requirements.is_file():
        blockers.append("Pinned SAM 2 requirements file is unavailable")
    if output.exists():
        blockers.append("Bootstrap script destination already exists")
    if not output.parent.is_dir():
        blockers.append("Bootstrap script parent directory does not exist")

    create_command = (
        f"py -{SAM2_PYTHON_VERSION} -m venv {_powershell_quote(environment)}"
    )
    pip_command = (
        f"& {_powershell_quote(python)} -m pip install --require-virtualenv "
        "--index-url https://download.pytorch.org/whl/cu128 "
        "torch==2.7.0 torchvision==0.22.0; "
        f"& {_powershell_quote(python)} -m pip install --require-virtualenv "
        f"-r {_powershell_quote(requirements)}"
    )
    checkpoint_command = (
        f"Download and verify {SAM2_CHECKPOINT_FILENAME} to "
        f"{_powershell_quote(checkpoint)}"
    )
    steps = (
        Sam2BootstrapStep("create_environment", "Create Python 3.12 environment", create_command, python.is_file()),
        Sam2BootstrapStep("install_packages", "Install pinned runtime packages", pip_command, False),
        Sam2BootstrapStep("install_checkpoint", "Download and verify checkpoint", checkpoint_command, checkpoint.is_file()),
        Sam2BootstrapStep("verify_runtime", "Run MotionAnchor readiness verification", "Run SAM 2 preflight in MotionAnchor", False),
    )
    return Sam2BootstrapPlan(
        schema_version=1,
        ready_to_generate=not blockers,
        target_python=str(python.resolve(strict=False)),
        requirements_path=str(requirements.resolve(strict=False)),
        checkpoint_path=str(checkpoint.resolve(strict=False)),
        checkpoint_url=SAM2_CHECKPOINT_URL,
        checkpoint_sha256=SAM2_CHECKPOINT_SHA256,
        script_path=str(output.resolve(strict=False)),
        blockers=tuple(blockers),
        steps=steps,
    )


def _script_text(plan: Sam2BootstrapPlan) -> str:
    environment, python, requirements, checkpoint = _target_paths()
    checkpoint_temp = checkpoint.with_suffix(".pt.download")
    return f'''# Generated by MotionAnchor. Review before execution.
$ErrorActionPreference = "Stop"
$EnvironmentPath = {_powershell_quote(environment)}
$PythonPath = {_powershell_quote(python)}
$RequirementsPath = {_powershell_quote(requirements)}
$CheckpointPath = {_powershell_quote(checkpoint)}
$CheckpointTempPath = {_powershell_quote(checkpoint_temp)}
$CheckpointUrl = "{SAM2_CHECKPOINT_URL}"
$ExpectedCheckpointSha256 = "{SAM2_CHECKPOINT_SHA256}"

if (-not (Test-Path -LiteralPath $PythonPath)) {{
    & py -{SAM2_PYTHON_VERSION} -m venv $EnvironmentPath
}}
if (-not (Test-Path -LiteralPath $PythonPath)) {{
    throw "Python 3.12 virtual environment creation failed."
}}
& $PythonPath -m pip install --upgrade pip
& $PythonPath -m pip install --require-virtualenv --index-url https://download.pytorch.org/whl/cu128 torch==2.7.0 torchvision==0.22.0
& $PythonPath -m pip install --require-virtualenv -r $RequirementsPath
'''


def _checkpoint_script() -> str:
    return '''
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $CheckpointPath) | Out-Null
$CheckpointValid = $false
if (Test-Path -LiteralPath $CheckpointPath) {
    $CurrentHash = (Get-FileHash -LiteralPath $CheckpointPath -Algorithm SHA256).Hash.ToLowerInvariant()
    $CheckpointValid = $CurrentHash -eq $ExpectedCheckpointSha256
}
if (-not $CheckpointValid) {
    Remove-Item -LiteralPath $CheckpointTempPath -Force -ErrorAction SilentlyContinue
    Invoke-WebRequest -UseBasicParsing -Uri $CheckpointUrl -OutFile $CheckpointTempPath
    $DownloadedHash = (Get-FileHash -LiteralPath $CheckpointTempPath -Algorithm SHA256).Hash.ToLowerInvariant()
    if ($DownloadedHash -ne $ExpectedCheckpointSha256) {
        Remove-Item -LiteralPath $CheckpointTempPath -Force -ErrorAction SilentlyContinue
        throw "SAM 2 checkpoint checksum mismatch."
    }
    Move-Item -LiteralPath $CheckpointTempPath -Destination $CheckpointPath -Force
}

Write-Host "SAM 2 runtime bootstrap completed."
Write-Host "Return to MotionAnchor and run Check GPU runtime."
'''


def write_sam2_bootstrap_script(script_path: str) -> dict[str, Any]:
    """Write a reviewable PowerShell script without executing it."""

    plan = build_sam2_bootstrap_plan(script_path)
    if not plan.ready_to_generate:
        raise ValueError("SAM 2 bootstrap plan is blocked: " + "; ".join(plan.blockers))
    target = Path(plan.script_path)
    text = _script_text(plan) + _checkpoint_script()
    target.write_text(text, encoding="utf-8", newline="\n")
    return {
        "plan": asdict(plan),
        "script_path": str(target.resolve()),
        "bytes_written": target.stat().st_size,
    }
